import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import ScrollRevealWrapper from "@/components/ScrollRevealWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
  // weight: ["400", "500", "600", "700"], // Optional: adjust as needed
});

export const metadata: Metadata = {
  title: "About Us - Anchor Bridge Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` min-h-screen flex flex-col ${leagueSpartan.variable} ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <ScrollRevealWrapper>
          <main className="flex-grow">{children}</main>
          <Footer />
        </ScrollRevealWrapper>
      </body>
    </html>
  );
}
